version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for submodules
  - package-ecosystem: gitsubmodule
    schedule:
      interval: "daily"
    directory: /

  # Maintain dependencies for rust
  - package-ecosystem: "cargo"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
