#!/bin/sh
# Vendors the subset of the official wasi-sdk sysroot that quickjs needs to
# link for the wasm32-unknown-unknown target: the prebuilt libc.a static
# archive, plus the headers needed to compile against it.
#
# Run this after bumping WASI_SDK_VERSION_MAJOR/MINOR (and updating
# WASI_SYSROOT_SHA256 from the new release's checksums) to pick up a newer
# wasi-sdk. Re-running it against an unchanged pin is a no-op: it always
# rebuilds sys/vendor/wasi-libc/ from scratch, so `git diff --exit-code` on
# that directory after running it is also how CI checks the vendored copy
# hasn't drifted from what the pinned version actually produces.
#
# Licensing: see sys/vendor/wasi-libc/NOTICE.md, generated by this script.

set -eu

WASI_SDK_VERSION_MAJOR=24
WASI_SDK_VERSION_MINOR=0
# sha256 of wasi-sysroot-24.0.tar.gz as published on the wasi-sdk-24 release:
# https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-24
WASI_SYSROOT_SHA256=35172f7d2799485b15a46b1d87f50a585d915ec662080f005d99153a50888f08

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
VENDOR_DIR="$REPO_ROOT/sys/vendor/wasi-libc"

# The exact subset of include/wasm32-wasi headers quickjs's C sources need to
# compile against wasi-libc's libc.a for this target, found by compiling
# libregexp.c, libunicode.c, quickjs.c, dtoa.c and wasm-shim/shim.c with
# `-MD -MF` dependency tracking and collecting the unique sysroot headers
# pulled in. If quickjs starts using a libc function whose header isn't in
# this list, the build fails with a missing-header compile error (not a
# silent bug) - rerun that probe and add whatever's missing.
HEADERS="
__fd_set.h
__functions_malloc.h
__functions_memcpy.h
__header_inttypes.h
__header_stdlib.h
__header_string.h
__header_time.h
__header_unistd.h
__macro_FD_SETSIZE.h
__macro_PAGESIZE.h
__seek.h
__struct_iovec.h
__struct_timespec.h
__struct_timeval.h
__struct_tm.h
__typedef_clock_t.h
__typedef_clockid_t.h
__typedef_fd_set.h
__typedef_sigset_t.h
__typedef_suseconds_t.h
__typedef_time_t.h
alloca.h
assert.h
bits/alltypes.h
bits/limits.h
bits/posix.h
bits/stdint.h
ctype.h
features.h
inttypes.h
limits.h
math.h
stdbool.h
stdint.h
stdio.h
stdlib.h
string.h
strings.h
sys/select.h
sys/time.h
time.h
unistd.h
"

work_dir=$(mktemp -d)
trap 'rm -rf "$work_dir"' EXIT

archive="$work_dir/wasi-sysroot-$WASI_SDK_VERSION_MAJOR.$WASI_SDK_VERSION_MINOR.tar.gz"
uri="https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-$WASI_SDK_VERSION_MAJOR/wasi-sysroot-$WASI_SDK_VERSION_MAJOR.$WASI_SDK_VERSION_MINOR.tar.gz"

echo "Downloading $uri"
curl --location --fail --retry 5 -o "$archive" "$uri"

if command -v sha256sum >/dev/null 2>&1; then
    actual_sha256=$(sha256sum "$archive" | cut -d' ' -f1)
else
    actual_sha256=$(shasum -a 256 "$archive" | cut -d' ' -f1)
fi
if [ "$actual_sha256" != "$WASI_SYSROOT_SHA256" ]; then
    echo "error: sha256 mismatch for $archive: expected $WASI_SYSROOT_SHA256, got $actual_sha256" >&2
    exit 1
fi

echo "Extracting"
tar -xzf "$archive" -C "$work_dir"
sysroot="$work_dir/wasi-sysroot-$WASI_SDK_VERSION_MAJOR.$WASI_SDK_VERSION_MINOR"

rm -rf "$VENDOR_DIR"
mkdir -p "$VENDOR_DIR/include" "$VENDOR_DIR/lib"

for h in $HEADERS; do
    mkdir -p "$VENDOR_DIR/include/$(dirname "$h")"
    cp "$sysroot/include/wasm32-wasi/$h" "$VENDOR_DIR/include/$h"
done

# wasi/api.h opens with an `#ifndef __wasi__` / `#error` guard, since it's
# only meant to be included when building for an actual wasi target. It's
# needed here too - quickjs's printf path reaches isatty/stdio backends
# declared there - so patch out just that one `#error`. Defining __wasi__
# instead is *not* an option: quickjs's __wasi__ path pins stack_limit = 0,
# disabling stack-overflow checking entirely.
mkdir -p "$VENDOR_DIR/include/wasi"
awk '
    /^#ifndef __wasi__/ { in_guard = 1 }
    /^#endif/ { in_guard = 0 }
    in_guard && /^#error/ { print "/* #error patched out by vendor-wasm-libc.sh for wasm32-unknown-unknown */"; next }
    { print }
' "$sysroot/include/wasm32-wasi/wasi/api.h" >"$VENDOR_DIR/include/wasi/api.h"

cp "$sysroot/lib/wasm32-wasi/libc.a" "$VENDOR_DIR/lib/libc.a"

cat >"$VENDOR_DIR/NOTICE.md" <<EOF
# Vendored wasi-libc

Vendored from the wasi-sdk-$WASI_SDK_VERSION_MAJOR release
(\`wasi-sysroot-$WASI_SDK_VERSION_MAJOR.$WASI_SDK_VERSION_MINOR.tar.gz\`,
sha256 \`$WASI_SYSROOT_SHA256\`) by \`scripts/vendor-wasm-libc.sh\`. This file is
regenerated deterministically from the pinned version above, so CI re-runs
the script and diffs the result to catch drift - it isn't hand-edited.

- \`lib/libc.a\`: the wasm32-wasi build of wasi-libc, unmodified.
- \`include/\`: the subset of wasi-libc's public headers that quickjs's C
  sources need to compile against \`libc.a\` for \`wasm32-unknown-unknown\`,
  with \`wasi/api.h\` carrying one commented-out \`#error\` (see the patch
  step in \`vendor-wasm-libc.sh\`) so it can be included outside an actual
  wasi target.

wasi-libc is licensed MIT / Apache-2.0 WITH LLVM-exception / Apache-2.0
(https://github.com/WebAssembly/wasi-libc/blob/main/LICENSE); wasi-sdk, which
builds and publishes this compiled artifact, is Apache-2.0 WITH LLVM-exception
(https://github.com/WebAssembly/wasi-sdk/blob/main/LICENSE). Both are
permissive with no copyleft terms; only \`libc.a\`'s object code and the
headers above are vendored here, not wasi-sdk's clang/LLVM toolchain.

To update: bump WASI_SDK_VERSION_MAJOR/MINOR and WASI_SYSROOT_SHA256 at the
top of vendor-wasm-libc.sh (the checksum is published on the release page,
https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-<major>), then
re-run the script from the repo root: \`sh scripts/vendor-wasm-libc.sh\`.
EOF

echo "Vendored into $VENDOR_DIR"
